server:

    # habilita recursão
    module-config: "validator iterator"

    # permite respostas maiores via UDP
    edns-buffer-size: 1232

    # segurança básica
    hide-identity: yes
    hide-version: yes

    # cache
    cache-min-ttl: 300
    cache-max-ttl: 86400

    # performance
    num-threads: 1
    msg-cache-size: 64m
    rrset-cache-size: 128m
