server:

    auto-trust-anchor-file: "/var/lib/unbound/root.key"

    module-config: "validator iterator"

    harden-dnssec-stripped: yes
    harden-below-nxdomain: yes
    harden-referral-path: yes

    val-clean-additional: yes
