server:

    module-config: "validator iterator"

    # Root hints de fallback
    root-hints: "/var/lib/unbound/root.hints"

    # Segurança
    hide-identity: yes
    hide-version: yes


auth-zone:

    name: "."

    zonefile: "/var/lib/unbound/root.zone"

    for-downstream: no
    for-upstream: yes
