server:

    # Cache otimizado ISP

    msg-cache-size: 256m
    rrset-cache-size: 512m

    cache-min-ttl: 300
    cache-max-ttl: 86400

    prefetch: yes
    prefetch-key: yes

    serve-expired: yes
    serve-expired-ttl: 86400

    num-threads: 2

    so-reuseport: yes
